from datetime import date, timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session

from .database import SessionLocal, engine
from .models import Base, Booking, Listing, ListingPhoto, Review, User


USERS = [
    {
        "name": "Maya Chen",
        "email": "maya@stay.com",
        "avatar_url": "https://i.pravatar.cc/150?img=47",
        "is_host": False,
        "is_superhost": False,
        "bio": "Weekend traveler who loves walkable neighborhoods and good coffee.",
        "joined_year": 2021,
    },
    {
        "name": "Jordan Blake",
        "email": "jordan@stay.com",
        "avatar_url": "https://i.pravatar.cc/150?img=12",
        "is_host": True,
        "is_superhost": True,
        "bio": "Superhost since 2018. I design calm, photo-ready homes for long stays.",
        "joined_year": 2016,
    },
    {
        "name": "Alex Rivera",
        "email": "alex@stay.com",
        "avatar_url": "https://i.pravatar.cc/150?img=33",
        "is_host": True,
        "is_superhost": True,
        "bio": "Architect and host. Expect thoughtful lighting and local restaurant tips.",
        "joined_year": 2017,
    },
    {
        "name": "Sam Okonkwo",
        "email": "sam@stay.com",
        "avatar_url": "https://i.pravatar.cc/150?img=15",
        "is_host": True,
        "is_superhost": False,
        "bio": "I open my family homes to guests who want a slower trip.",
        "joined_year": 2020,
    },
]


LISTINGS = [
    {
        "host_email": "jordan@stay.com",
        "title": "Sunlit loft above Canal Saint-Martin",
        "description": "A bright Paris loft with herringbone floors, a chef's kitchen, and a balcony that catches late-afternoon light. Walk to bakeries, bookshops, and the canal in under five minutes. Perfect for couples or a small family who want a neighborhood stay rather than a hotel corridor.",
        "city": "Paris",
        "country": "France",
        "address": "Canal Saint-Martin, 10th arrondissement",
        "lat": 48.8711,
        "lng": 2.3656,
        "price_per_night": 248,
        "cleaning_fee": 65,
        "property_type": "Entire home",
        "category": "Design",
        "guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1.5,
        "amenities": "Wifi,Kitchen,Washer,Dryer,Air conditioning,Dedicated workspace,Hair dryer,Coffee maker",
        "photos": [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600",
            "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1600",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1600",
            "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1600",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600",
        ],
    },
    {
        "host_email": "alex@stay.com",
        "title": "Cliffside villa with infinity pool",
        "description": "Wake up over the Aegean. This whitewashed villa has an infinity pool, outdoor dining terrace, and sunset views that stop conversation. The village bakery is a short walk down the caldera path.",
        "city": "Oia",
        "country": "Greece",
        "address": "Caldera path, Oia, Santorini",
        "lat": 36.4618,
        "lng": 25.3753,
        "price_per_night": 620,
        "cleaning_fee": 120,
        "property_type": "Entire home",
        "category": "Amazing views",
        "guests": 6,
        "bedrooms": 3,
        "beds": 3,
        "bathrooms": 3,
        "amenities": "Wifi,Pool,Kitchen,Air conditioning,Free parking,Hot tub,BBQ grill,Beach essentials",
        "photos": [
            "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1600",
            "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1600",
            "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1600",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1600",
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600",
        ],
    },
    {
        "host_email": "sam@stay.com",
        "title": "Bamboo house in the rice fields",
        "description": "Open-air living among Ubud's rice terraces. Outdoor shower, yoga deck, and a private chef on request. Birds at dawn, fireflies at night.",
        "city": "Ubud",
        "country": "Indonesia",
        "address": "Tegalalang, Ubud, Bali",
        "lat": -8.4312,
        "lng": 115.2793,
        "price_per_night": 175,
        "cleaning_fee": 40,
        "property_type": "Entire home",
        "category": "Tropical",
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "amenities": "Wifi,Kitchen,Pool,Free parking,Workspace,Breakfast,Outdoor shower",
        "photos": [
            "https://images.unsplash.com/photo-1537996194471-e657df975ab2?w=1600",
            "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=1600",
            "https://images.unsplash.com/photo-1540541338287-41700290dde6?w=1600",
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1600",
        ],
    },
    {
        "host_email": "jordan@stay.com",
        "title": "Brownstone garden apartment",
        "description": "A garden-level Brooklyn brownstone with original millwork, a rain shower, and a private patio. Subway two blocks away; coffee on the stoop in the morning.",
        "city": "Brooklyn",
        "country": "United States",
        "address": "Fort Greene, Brooklyn",
        "lat": 40.6895,
        "lng": -73.9741,
        "price_per_night": 289,
        "cleaning_fee": 75,
        "property_type": "Entire home",
        "category": "Cities",
        "guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1,
        "amenities": "Wifi,Kitchen,Washer,Dryer,Heating,Workspace,TV,Coffee maker",
        "photos": [
            "https://images.unsplash.com/photo-1501183638710-841dd1904471?w=1600",
            "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600",
            "https://images.unsplash.com/photo-1560185127-6ed189bf61f0?w=1600",
            "https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=1600",
        ],
    },
    {
        "host_email": "alex@stay.com",
        "title": "Minimalist cabin by the lake",
        "description": "Floor-to-ceiling glass, a wood stove, and a dock for morning swims. The nearest neighbor is a heron. Bring a book and stay a week.",
        "city": "Lake Tahoe",
        "country": "United States",
        "address": "West Shore, Lake Tahoe",
        "lat": 39.0968,
        "lng": -120.0324,
        "price_per_night": 340,
        "cleaning_fee": 90,
        "property_type": "Entire home",
        "category": "Cabins",
        "guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 2,
        "amenities": "Wifi,Kitchen,Fireplace,Free parking,Lake access,Heating,BBQ grill,Washer",
        "photos": [
            "https://images.unsplash.com/photo-1449158349943-36dbaadb50df?w=1600",
            "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600",
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600",
            "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1600",
            "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1600",
        ],
    },
    {
        "host_email": "sam@stay.com",
        "title": "Riads courtyard with a fountain",
        "description": "A restored riad around a tiled courtyard. Breakfast is served under the orange tree. The medina is a maze; I'll send you a walking map.",
        "city": "Marrakesh",
        "country": "Morocco",
        "address": "Medina, Marrakesh",
        "lat": 31.6295,
        "lng": -7.9811,
        "price_per_night": 198,
        "cleaning_fee": 50,
        "property_type": "Entire home",
        "category": "Design",
        "guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 3,
        "amenities": "Wifi,Kitchen,Air conditioning,Breakfast,Patio,Hair dryer,Workspace",
        "photos": [
            "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=1600",
            "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=1600",
            "https://images.unsplash.com/photo-1548013146-72479768bada?w=1600",
            "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1600",
            "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1600",
        ],
    },
    {
        "host_email": "jordan@stay.com",
        "title": "Shibuya studio with skyline nightcaps",
        "description": "Compact Tokyo studio, floor bed, and a window that frames the crossing. Convenience store downstairs, ramen two streets over.",
        "city": "Tokyo",
        "country": "Japan",
        "address": "Shibuya, Tokyo",
        "lat": 35.6595,
        "lng": 139.7004,
        "price_per_night": 156,
        "cleaning_fee": 35,
        "property_type": "Entire home",
        "category": "Cities",
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "amenities": "Wifi,Kitchen,Washer,Air conditioning,Workspace,TV,Self check-in",
        "photos": [
            "https://images.unsplash.com/photo-1490806844420-4ea91b82d51b?w=1600",
            "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600",
            "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=1600",
            "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1600",
        ],
    },
    {
        "host_email": "alex@stay.com",
        "title": "Beach bungalow on stilts",
        "description": "Sand under the house, hammock on the deck, and the ocean 30 steps away. Snorkel gear is in the closet. No shoes required.",
        "city": "Tulum",
        "country": "Mexico",
        "address": "Beach road, Tulum",
        "lat": 20.2114,
        "lng": -87.4654,
        "price_per_night": 265,
        "cleaning_fee": 55,
        "property_type": "Entire home",
        "category": "Beach",
        "guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2,
        "amenities": "Wifi,Kitchen,Beach access,Air conditioning,Free parking,BBQ grill,Outdoor shower",
        "photos": [
            "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1600",
            "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1600",
            "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600",
            "https://images.unsplash.com/photo-1471922694854-ff1b8b9df5db?w=1600",
            "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=1600",
        ],
    },
    {
        "host_email": "sam@stay.com",
        "title": "Alpine chalet with a wood-fired sauna",
        "description": "Ski-in access in winter, hiking trails in summer. The sauna looks at the valley. Fondue pot included, obviously.",
        "city": "Zermatt",
        "country": "Switzerland",
        "address": "Winkelmatten, Zermatt",
        "lat": 46.0207,
        "lng": 7.7491,
        "price_per_night": 410,
        "cleaning_fee": 95,
        "property_type": "Entire home",
        "category": "Skiing",
        "guests": 8,
        "bedrooms": 4,
        "beds": 6,
        "bathrooms": 3,
        "amenities": "Wifi,Kitchen,Fireplace,Free parking,Washer,Heating,Ski-in,Sauna",
        "photos": [
            "https://images.unsplash.com/photo-1520986606214-8b456906c813?w=1600",
            "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1600",
            "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1600",
            "https://images.unsplash.com/photo-1513519245088-0e12902e35a0?w=1600",
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600",
        ],
    },
    {
        "host_email": "jordan@stay.com",
        "title": "Tiny house in the English countryside",
        "description": "A 28-square-meter tiny house on a working farm. Sheep for neighbors, a compost toilet done right, and the best eggs of your life.",
        "city": "Cotswolds",
        "country": "United Kingdom",
        "address": "Near Stow-on-the-Wold",
        "lat": 51.9306,
        "lng": -1.7231,
        "price_per_night": 132,
        "cleaning_fee": 30,
        "property_type": "Entire home",
        "category": "Tiny homes",
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "amenities": "Wifi,Kitchen,Free parking,Heating,Workspace,Fire pit,Garden",
        "photos": [
            "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1600",
            "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1600",
            "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1600",
            "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1600",
            "https://images.unsplash.com/photo-1416331108676-a1ea98a936f5?w=1600",
        ],
    },
    {
        "host_email": "alex@stay.com",
        "title": "Gothic quarter penthouse terrace",
        "description": "A rooftop in the Gothic Quarter with a long table for late dinners. Cathedral bells, vermouth hour, and a rain shower with a sky view.",
        "city": "Barcelona",
        "country": "Spain",
        "address": "Barri Gòtic, Barcelona",
        "lat": 41.3825,
        "lng": 2.1769,
        "price_per_night": 275,
        "cleaning_fee": 70,
        "property_type": "Entire home",
        "category": "Cities",
        "guests": 5,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 2,
        "amenities": "Wifi,Kitchen,Washer,Air conditioning,Workspace,TV,Patio,Coffee maker",
        "photos": [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600",
            "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600",
        ],
    },
    {
        "host_email": "sam@stay.com",
        "title": "Hillside bungalow above Camps Bay",
        "description": "Twelve Apostles in the morning, Atlantic sunsets at night. Indoor-outdoor living, a plunge pool, and a path down to the beach.",
        "city": "Cape Town",
        "country": "South Africa",
        "address": "Camps Bay, Cape Town",
        "lat": -33.9510,
        "lng": 18.3770,
        "price_per_night": 310,
        "cleaning_fee": 80,
        "property_type": "Entire home",
        "category": "Amazing views",
        "guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2,
        "amenities": "Wifi,Kitchen,Pool,Free parking,Air conditioning,BBQ grill,Washer,Beach essentials",
        "photos": [
            "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1600",
            "https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?w=1600",
            "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1600",
            "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=1600",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1600",
        ],
    },
    {
        "host_email": "jordan@stay.com",
        "title": "Lakeside farmhouse with a boat",
        "description": "A restored farmhouse on Lake Bolsena. Rowboat included. The village market is Thursday mornings; I'll leave espresso and a map.",
        "city": "Bolsena",
        "country": "Italy",
        "address": "Lake Bolsena, Lazio",
        "lat": 42.6440,
        "lng": 11.9857,
        "price_per_night": 220,
        "cleaning_fee": 60,
        "property_type": "Entire home",
        "category": "Lakes",
        "guests": 8,
        "bedrooms": 4,
        "beds": 5,
        "bathrooms": 3,
        "amenities": "Wifi,Kitchen,Free parking,Washer,Fireplace,Lake access,BBQ grill,Garden",
        "photos": [
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600",
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600",
            "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1600",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600",
        ],
    },
    {
        "host_email": "alex@stay.com",
        "title": "Glass treehouse in the rainforest",
        "description": "Sleep in the canopy. A glass treehouse with a hanging bed, outdoor bath, and howler monkeys as the alarm clock.",
        "city": "La Fortuna",
        "country": "Costa Rica",
        "address": "Near Arenal Volcano",
        "lat": 10.4678,
        "lng": -84.6427,
        "price_per_night": 188,
        "cleaning_fee": 42,
        "property_type": "Entire home",
        "category": "Countryside",
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "amenities": "Wifi,Kitchen,Free parking,Outdoor shower,Hot tub,Workspace,Garden",
        "photos": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1600",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1600",
            "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1600",
            "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1600",
            "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1600",
        ],
    },
    {
        "host_email": "sam@stay.com",
        "title": "Harbour loft with crane views",
        "description": "Converted warehouse loft facing the harbour. High ceilings, concrete, and a record player. Pubs downstairs, ferries two minutes away.",
        "city": "Sydney",
        "country": "Australia",
        "address": "Walsh Bay, Sydney",
        "lat": -33.8550,
        "lng": 151.2050,
        "price_per_night": 295,
        "cleaning_fee": 72,
        "property_type": "Entire home",
        "category": "Cities",
        "guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1,
        "amenities": "Wifi,Kitchen,Washer,Air conditioning,Workspace,TV,Gym,Self check-in",
        "photos": [
            "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1600",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600",
            "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600",
        ],
    },
    {
        "host_email": "jordan@stay.com",
        "title": "Private room in a Lisbon azulejo flat",
        "description": "A quiet private room in a tiled Alfama apartment. Shared kitchen, rooftop for sunset, and trams that rattle past like a film score.",
        "city": "Lisbon",
        "country": "Portugal",
        "address": "Alfama, Lisbon",
        "lat": 38.7118,
        "lng": -9.1304,
        "price_per_night": 89,
        "cleaning_fee": 20,
        "property_type": "Private room",
        "category": "Cities",
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "amenities": "Wifi,Kitchen,Washer,Heating,Hair dryer,Workspace",
        "photos": [
            "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1600",
            "https://images.unsplash.com/photo-1513735492246-483525079686?w=1600",
            "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=1600",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600",
            "https://images.unsplash.com/photo-1501183638710-841dd1904471?w=1600",
        ],
    },
]


REVIEWS = [
    (1, "maya@stay.com", 4.9, "The balcony light at 6pm is unfair. Jordan's bakery list was perfect."),
    (1, "sam@stay.com", 4.8, "Quiet, beautiful, and exactly as photographed."),
    (2, "maya@stay.com", 5.0, "We watched the sun drop into the caldera every night. Unreal."),
    (3, "jordan@stay.com", 4.7, "Woke up to mist over the rice fields. Outdoor shower is a highlight."),
    (4, "alex@stay.com", 4.85, "Felt like a friend's place. Patio coffee became a ritual."),
    (5, "maya@stay.com", 4.95, "The dock at sunrise. We barely left the cabin."),
    (6, "jordan@stay.com", 4.8, "Courtyard breakfast was the trip. Helpful walking notes."),
    (7, "sam@stay.com", 4.6, "Tiny but clever. Location makes it."),
    (8, "maya@stay.com", 4.9, "Hammock, salt air, no agenda. Booked it again in my head."),
    (9, "alex@stay.com", 4.85, "Sauna after skiing is the whole point. Spotless chalet."),
    (10, "maya@stay.com", 4.7, "Sheep symphony at dusk. Tiny house done with care."),
    (11, "jordan@stay.com", 4.9, "Terrace dinners with cathedral bells. Magic."),
    (12, "maya@stay.com", 4.8, "Views that make you late for dinner reservations."),
    (13, "alex@stay.com", 4.75, "Rowed at golden hour. House feels lived-in, in the best way."),
    (14, "maya@stay.com", 5.0, "Rain on the glass roof. I would live here."),
    (15, "jordan@stay.com", 4.7, "Harbour light is cinematic. Great records, too."),
    (16, "alex@stay.com", 4.65, "Private room was quiet; rooftop sunset is the win."),
]


def seed(db: Session, reset: bool = False) -> None:
    if reset:
        Base.metadata.drop_all(bind=engine)
        Base.metadata.create_all(bind=engine)

    if db.scalar(select(User.id).limit(1)):
        return

    users_by_email: dict[str, User] = {}
    for row in USERS:
        user = User(**row)
        db.add(user)
        db.flush()
        users_by_email[user.email] = user

    listing_rows: list[Listing] = []
    for row in LISTINGS:
        host = users_by_email[row["host_email"]]
        photos = row["photos"]
        listing = Listing(
            host_id=host.id,
            title=row["title"],
            description=row["description"],
            city=row["city"],
            country=row["country"],
            address=row["address"],
            lat=row["lat"],
            lng=row["lng"],
            price_per_night=row["price_per_night"],
            cleaning_fee=row["cleaning_fee"],
            service_fee=0,
            property_type=row["property_type"],
            category=row["category"],
            guests=row["guests"],
            bedrooms=row["bedrooms"],
            beds=row["beds"],
            bathrooms=row["bathrooms"],
            amenities=row["amenities"],
            cover_image=photos[0],
        )
        db.add(listing)
        db.flush()
        for i, url in enumerate(photos):
            db.add(ListingPhoto(listing_id=listing.id, url=url, sort_order=i))
        listing_rows.append(listing)

    today = date.today()
    maya = users_by_email["maya@stay.com"]
    db.add(
        Booking(
            listing_id=listing_rows[1].id,
            guest_id=maya.id,
            check_in=today + timedelta(days=12),
            check_out=today + timedelta(days=16),
            guests=2,
            nights=4,
            subtotal=listing_rows[1].price_per_night * 4,
            cleaning_fee=listing_rows[1].cleaning_fee,
            service_fee=140,
            total=listing_rows[1].price_per_night * 4 + listing_rows[1].cleaning_fee + 140,
            status="confirmed",
        )
    )
    db.add(
        Booking(
            listing_id=listing_rows[3].id,
            guest_id=maya.id,
            check_in=today - timedelta(days=40),
            check_out=today - timedelta(days=36),
            guests=2,
            nights=4,
            subtotal=listing_rows[3].price_per_night * 4,
            cleaning_fee=listing_rows[3].cleaning_fee,
            service_fee=160,
            total=listing_rows[3].price_per_night * 4 + listing_rows[3].cleaning_fee + 160,
            status="completed",
        )
    )
    db.add(
        Booking(
            listing_id=listing_rows[0].id,
            guest_id=maya.id,
            check_in=today + timedelta(days=3),
            check_out=today + timedelta(days=6),
            guests=2,
            nights=3,
            subtotal=listing_rows[0].price_per_night * 3,
            cleaning_fee=listing_rows[0].cleaning_fee,
            service_fee=104,
            total=listing_rows[0].price_per_night * 3 + listing_rows[0].cleaning_fee + 104,
            status="confirmed",
        )
    )

    for listing_index, email, rating, comment in REVIEWS:
        listing = listing_rows[listing_index - 1]
        author = users_by_email[email]
        db.add(
            Review(
                listing_id=listing.id,
                user_id=author.id,
                rating=rating,
                comment=comment,
            )
        )

    db.commit()


if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    session = SessionLocal()
    try:
        seed(session, reset=True)
        print("Database seeded.")
    finally:
        session.close()
